# SPDX-License-Identifier: GPL-2.0
#
# Kbuild for the devwh audit rebuild.
# Used by `make -C $KDIR M=$(CURDIR) modules` (see Makefile).

obj-m += devwh.o

devwh-y := \
	main.o     \
	rand.o     \
	kallsyms.o \
	hide.o     \
	memrw.o    \
	hwbp.o     \
	fops.o

ccflags-y += -I$(src) -Wall -Wno-unused-function -Wno-unused-variable
